# Generated by Django 5.0.6 on 2024-07-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worked_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hours',
            field=models.DurationField(verbose_name='Hours spent per date'),
        ),
    ]
