# Generated by Django 5.0.6 on 2024-07-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worked_hours', '0003_alter_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hours',
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Project date')),
                ('hours', models.DurationField(verbose_name='Hours spent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worked_hours.project')),
            ],
        ),
    ]
