# Generated by Django 5.0.6 on 2024-07-10 10:30

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worked_hours', '0004_remove_project_date_remove_project_hours_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, verbose_name='Company name')),
                ('company_number', models.IntegerField(verbose_name='Company number')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Street name and number')),
                ('zip', models.IntegerField(blank=True, null=True, verbose_name='Zip code')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hours',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of project'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worked_hours.company'),
        ),
    ]
