# Generated by Django 5.0.6 on 2024-07-29 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worked_hours', '0006_timecard_delete_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecard',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='timecard',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ending time of day'),
        ),
        migrations.AddField(
            model_name='timecard',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting time of day'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=27000), verbose_name='Time spent'),
        ),
    ]
